"""
FDM_restriction_check.py Loads .npz's generated by FDM_restriction.py to check.
"""
import numpy as np
import matplotlib.pyplot as plt
IC="2"

data_restricted = np.load(f"src/burgers_solbased/Burgers_IC_{IC}.npz")
t_restricted, x_restricted, u_restricted = data_restricted["t"], data_restricted["x"], data_restricted["usol"]

print(u_restricted.shape)
print(x_restricted.shape)
print(t_restricted.shape)
# -- -- -- -- -- -- -- -- -- --
# Plot the original and reduced matrices

plt.figure(figsize=(12, 6))
plt.imshow(u_restricted, extent=[0, 1, -1, 1], aspect='auto', cmap='rainbow')
plt.title('Reduced Matrix')
plt.colorbar()
plt.show()